# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/buildpack-deps:stretch
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    environment:
      QTDIR: /opt/qt/6.2.0/msvc2019_64
      PATH: $QTDIR/bin:$PATH
    steps:
      - checkout
      - run: apt-get update && apt-get install -y qt6-default qt6-qmake qt6-base qt6-tools qt6-svg qt6-xmlpatterns qt6-winextras cmake
      - run: cmake -DCMAKE_PREFIX_PATH=$QTDIR -DCMAKE_BUILD_TYPE=Release -G Ninja -B build
      - run: cmake --build build

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
